# Generated by Django 3.1.1 on 2022-05-19 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=10)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
