# Generated by Django 3.1.1 on 2022-05-19 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='idCompra',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipoPagamento',
            field=models.CharField(max_length=15),
        ),
    ]
